version: '3.8'

services:
  mysqldb: 
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - ./.env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysqlVolume:/lib/mysql
      - mysqlConfig:/etc/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
  docker-python:
    build:
      context: .
    ports:
      - 3000:5000
    volumes:
      - ./src:/app/src
    depends_on:
      - mysqldb

volumes:
  mysqlVolume:
  mysqlConfig: